# Generated by Django 3.2.10 on 2024-09-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FonoMuzika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
                ('failas', models.FileField(upload_to='fono_muzika/')),
            ],
        ),
        migrations.CreateModel(
            name='Sveikinimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekstas', models.TextField()),
                ('garso_failas', models.FileField(upload_to='garso_failai/')),
                ('paveikslelis', models.ImageField(upload_to='paveiksleliai/')),
                ('galutinis_failas', models.FileField(upload_to='galutiniai_failai/')),
                ('sukurimo_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
